### PR TITLE
Remove leftover jbuild file and upgrades to Dune 2.0

### PR DESCRIPTION
**Pull request by ManasJayanth**

### CODE REVIEW

**Comment by cdaringe** [comment]
image

Hey, look at that. It compiles 😌

**Comment by cdaringe** [comment]
@bobbypriambodo , mind merging this ASAP? @ManasJayanth pruned his fork, and my build fell apart :)

**Comment by ManasJayanth** [comment]
Apologies :)

**Comment by bobbypriambodo** [comment]
Hi folks, sorry I didn't notice this PR before.

Just asking since I'm not currently working on OCaml and haven't got into Dune 2.0 yet, will this change break older builds?

**Comment by bobbypriambodo** [comment]
Also will this solve #5?

**Comment by bobbypriambodo** [comment]
You know what, since you've been using it since September, I'll just assume that it works and will handle problems separately.

Thanks for the PR!

**Pull request merged**
